### ISSUE TITLE
UINibを指定して広告テンプレートを登録したい

### ISSUE THREAD

**Issue by akuraru** [amoad/amoad-ios-sdk#120]
- (void)registerTableView:(UITableView *)tableView sid:(NSString *)sid tag:(NSString *)tag nibName:(NSString *)nibName;

においてnibNameを指定して広告テンプレートを登録しているが、これは [NSBundle mainBundle] を想定されているように思える。この場合、mainBundle 以外の（例えば外部ライブラリによってBundleが異なる場合で）広告テンプレートを読み込むことができない。nibNameではなく、nib自体を登録できるメソッドがあってほしい

**Comment by hashikell** [comment]
@akuraru 諸々、対応が遅れており申し訳ございません。
こちらはすぐにでも対応できるかと思います。

完了次第、ご連絡させていただきます。
よろしくお願いします。

**Comment by hashikell** [comment]
@akuraru Pre-Releaseとして公開いたしました。
https://github.com/amoad/amoad-ios-sdk/releases/tag/v3.9.5
ご確認ください。

ドキュメントとサンプルコードが完成して、
リリーステストに問題がなければ、正式リリースとする予定です。

**Comment by akuraru** [comment]
私が望んだ機能は実装されていることを確認しました

**Comment by hashikell** [comment]
@akuraru ドキュメントも更新しましたので、完了とさせていただきます。

**Comment by akuraru** [comment]
ありがとうございます
