### ISSUE TITLE
XCODE Archiveの時だけエラーが出る

### ISSUE THREAD

**Issue by Omokuro** [amoad/amoad-ios-sdk#196]
iOSシミュレーターでも実機テストでも問題ないのに、Archiveしようとすると、
linker command failed with exit code 1 (use -v to see invocation)
のエラーが出るため、先に進めません。
bitcode bundle could not be generated because '............./libAMoAd.a(AMoAdNativeViewItem.o)' was built without full bitcode.
というのが原因なんだそうですが、何か思い当たる対処方法をご存知でしたら教えて下さい。

**Comment by Omokuro** [comment]
iOSシミュレーターでも実機テストでも問題ないのに、Archiveしようとすると、
linker command failed with exit code 1 (use -v to see invocation)
のエラーが出るため、先に進めません。
bitcode bundle could not be generated because '............./libAMoAd.a(AMoAdNativeViewItem.o)' was built without full bitcode.
というのが原因なんだそうですが、何か思い当たる対処方法をご存知でしたら教えて下さい。

**Comment by hashikell** [comment]
@Omokuro ご連絡ありがとうございます。調査します。

**Comment by Omokuro** [comment]
TARGETSの設定からBuild Settings => Build Options => Enable BitcodeをNoにすることで解決しました。

情報ソース：
http://akataworks.hatenadiary.jp/entry/2015/09/18/161812

**Comment by hashikell** [comment]
@Omokuro 

貴重な情報をありがとうございます。
Bitcodeの対応を検討しようと思います。

情報ソース:
http://hikaruapp.jpn.com/xcode/ochame/post-718
