### ISSUE TITLE
Xcode11.4.1でswift compiler error

### ISSUE THREAD

**Issue by doihei** [amoad/amoad-ios-sdk#254]
## 概要
AmoAdをcocoapodsでインストールしていまして下記の
Module compileエラーが発生します。ご対応いただけると幸いです。

## エラー内容
```
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2.2 compiler
```

## 環境
- MacOS 10.15.4
- Xcode11.4.1(11E503a)
- AMoAd SDK v6.0.3

**Comment by tko3** [comment]
AMoAdSDK v6.0.4をリリースいたしましたのでそちらでご確認ください

**Comment by doihei** [comment]
ご対応ありがとうございます。
xcode11.4.1環境でのビルド確認できました。
