### ISSUE TITLE
Xcode14.1でコンパイルエラー

### ISSUE THREAD

**Issue by MasatomoFukuda** [amoad/amoad-ios-sdk#276]
## 概要
お世話様です。
Xcode14.1で下記エラーが出ております。
こちらご対応いただければ幸いです。

#254 と同種のイシューと思われます。

## エラー内容
> Module compiled with Swift 5.7 cannot be imported by the Swift 5.7.1 compiler

## 環境
macOS 12.6
Xcode 14.1
AMoAd SDK v6.1.9

**Comment by seiginakamura0714** [comment]
@MasatomoFukuda 
ご指摘ありがとうございます。
こちら早急に対応致します。

**Comment by MasatomoFukuda** [comment]
@seiginakamura0714 
ご確認ありがとうございます。
よろしくお願いします！

**Comment by seiginakamura0714** [comment]
@MasatomoFukuda 
#277 こちらのPRで最新バージョンのXcode14.2に対応させていただきました。
AMoAdSDK v6.1.11 を導入していただき、Xcode14.2環境下でご確認のほどよろしくお願いいたします。

**Comment by MasatomoFukuda** [comment]
@seiginakamura0714 
確認させていただき問題ございませんでした。
早急なご対応、誠にありがとうございます！
