### ISSUE TITLE
Xcode15でコンパイルエラー

### ISSUE THREAD

**Issue by ichikawa7ss** [amoad/amoad-ios-sdk#288]
お世話になっております。

Xcode15.0.1で以下のコンパイルエラーが出ております。

```Compiled module was created by a different version of the compiler ''; rebuild 'AMoAd' and try again: /Users/{user}/{project}/Pods/AMoAd/AMoAd.framework/Modules/AMoAd.swiftmodule/arm64-apple-ios.swiftmodule```

こちらXcode15の互換性が無いようでして、ご確認いただけますと幸いです。

### 利用環境
- macOS 13.6.3
- Xcode 15.0.1
- AMoAd SDK v6.1.12
    - 6.1.17でも確認しましたが```No such module 'AmoAd'```のエラーとなりました

**Comment by seiginakamura0714** [comment]
@ichikawa7ss 

お世話になっております。AMoAdエンジニアの中村と申します。
お手数ですがこちら「Link Binary With Libraries」にAMoAd.xcframeworkを追加してbuild試していただいてもよろしいでしょうか?
![スクリーンショット 2023-12-20 17 06 58](https://github.com/amoad/amoad-ios-sdk/assets/104749603/dfe0dee5-5a7e-41b4-a474-b37fecad155d)

**Comment by ichikawa7ss** [comment]
@seiginakamura0714 
早速ご回答ありがとうございます。
ご教示いただいた内容でエラーが解消されました。
ありがとうございます！

issueはcloseいたします🙇‍♂️

**Comment by seiginakamura0714** [comment]
@ichikawa7ss 
ご対応ありがとうございました。
引き続きよろしくお願いします！
