### ISSUE TITLE
成功した場合の処理

### ISSUE THREAD

**Issue by akuraru** [amoad/amoad-ios-sdk#60]
広告が取得できたタイミングで処理を行いたいが、そのようなデリゲートが見当たらない。どうしたら良いでしょうか？

**Comment by hashikell** [comment]
@akuraru 

以下の3タイミングでコールバックするよう改善いたします。

1. テキスト情報の取得に成功した
2. アイコン画像の取得に成功した
3. メイン画像の取得に成功した

以下の3つのケースがあるため、
**どのデリゲートで成功と判定するかはデベロッパ様に委ねる**こととします。

A. 広告タイプが「アイコン＋テキスト」であっても、
アイコンを使用するかどうかSDKではわからない（二行テキスト）。

B. 広告タイプが「メイン画像＋テキスト」であっても、
アイコンを使用するかどうかSDKではわからない。

C. 広告タイプが「メイン画像＋テキスト」であっても、
アイコン、およびテキストを使用するかどうかSDKではわからない。

**Comment by akuraru** [comment]
私としては十分です。よろしくお願いします。

**Comment by hashikell** [comment]
https://github.com/amoad/amoad-ios-sdk/pull/65 v3.6.2にて、「1. テキスト情報の取得に成功した」のみ対応しました。

**Comment by hashikell** [comment]
v3.7.1 ですべて対応いたしました。
