### ISSUE TITLE
テキストのみを取得したい

### ISSUE THREAD

**Issue by akuraru** [amoad/amoad-ios-sdk#61]
UIAlertViewなどでテキストのみを表示したい。その場合、無駄なViewを生成してしまう。何らかのオブジェクトで広告のデータを返してほしい。

**Comment by hashikell** [comment]
@akuraru 

> UIAlertViewなどでテキストのみを表示

というのが規約として問題ないか確認いたします。

**Comment by hashikell** [comment]
@akuraru こちらの件につきまして、メディア様アカウントをお持ちかと思いますので、そちらの窓口のほうからお問い合わせいただけますでしょうか。「ネイティブ広告のUIAlertView表示の件」とおっしゃっていただければ分かるようになっております。よろしくお願いいたします。

**Comment by akuraru** [comment]
@hashikell 了解しました。ありがとうございます

**Comment by hashikell** [comment]
実装着手、遅れています。
あえてmilestoneを変えず、できるだけ早期のリリースを目指します。
