### ISSUE TITLE
impについて

### ISSUE THREAD

**Issue by akuraru** [amoad/amoad-ios-sdk#89]
`- (void)prepareAdWithSid:(NSString *)sid;` を実行した時点で、imp数が増加することがわかりました。レンダリングする際もimp数がカウントされるため不当に高いimp数になってしまっています。

`- (void)prepareAdWithSid:(NSString *)sid;` の時点でimp数を増加させなくするか、`- (void)prepareAdWithSid:(NSString *)sid;` なしにレンダリングする方法はありますか？

**Comment by hashikell** [comment]
@akuraru ご指摘いただきました件、こちらでは確認できません。

どのような方法で確認されましたでしょうか？


以下のトレース設定で、

```objc
  [AMoAdLogger sharedLogger].trace = YES; // YES...トレース出力ON
```

以下のトレースログが出力されるかと思います。

impression sending...
impression sending...complete!


こちらでは、Charles（プロキシ）でも確認していますので、間違いないかと思います。


また、同じURLのimpを何度送ってもサーバ側で重複排除しますので、
厳重にチェックはしておりませんが、管理画面上は正しい数字になっているかと思います。

**Comment by akuraru** [comment]
トレースの方法了解です。再現方法を確認するのでお待ちください

**Comment by akuraru** [comment]
再現手順
`- (void)prepareAdWithSid:(NSString *)sid;` 実行する
2, 3時間後、imp数を確認する

このとき、ログには `ad call: 〜` のみが表示され `impression sending...` を表示させていない。

**Comment by hashikell** [comment]
@akuraru 
再現手順を鑑みるに、あり得るとしたらサーバ側の問題かと思われます。
枠IDなどを教えていただきたいので、メールにてご連絡させていただきます。

**Comment by akuraru** [comment]
現状、下記のような仕様とのことでした。
・prepareAdを単体で実行した場合、1PVとしてカウントされ、管理画面上1impとして扱われる。
・prepareAdとrenderAdが十分に短い間に行われ規定回数以下の場合、1PVとしてカウントされ、管理画面上1impとして扱われる。
・問い合わせれば、renderAdの回数をimpの回数として扱えるように設定を変更してくれる
